version: "3.9"

services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "50051:50051"

  postgres:
    image: postgres:17
    container_name: users-db
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/user-service/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  api-gateway:
    build: ./services/api-gateway
    env_file:
      - ./services/api-gateway/.env
    container_name: api-gateway
    ports:
      - "8080:8080"

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

volumes:
    postgres-data:
    minio-data:
