version: "3.9"

services:
  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "50051:50051"

  api-gateway:
    build: ./services/api-gateway
    env_file:
      - ./services/api-gateway/.env
    container_name: api-gateway
    ports:
      - "8080:8080"
