version: "3.9"

services:
  db-service:
    build: services/db-service
    container_name: db-service
    ports:
      - "50051:50051"

  postgres:
    image: postgres:17
    container_name: database
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./services/db-service/migrations/init.sql:/docker-entrypoint-initdb.d/init.sql

  api-gateway:
    build: ./services/api-gateway
    env_file:
      - ./services/api-gateway/.env
    container_name: api-gateway
    ports:
      - "8080:8080"

  orchestrator:
    build: ./services/orchestrator
    container_name: orchestrator
    ports:
      - "8081:8081"
    depends_on:
      - db-service
      - api-gateway

  barpath:
    build: ./services/barpath
    container_name: barpath
    depends_on:
      - rabbitmq
      - minio
      - orchestrator
    volumes:
      - ./services/barpath/runs:/app/runs
    environment:
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: admin123
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_HEARTBEAT: 900

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"

volumes:
    postgres-data:
    minio-data:
